services:

  backend:
    build: ./backend

    ports:
      - "5001:5000"

    volumes:
      - ./backend:/app
      - ./backend/deployments:/app/deployments
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      postgres:
        condition: service_healthy

    restart: always

  postgres:
    image: postgres:17

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deployment_platform

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: